{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ASTITeam",
    "module": "poslocator",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "poslocator-1.0.4.aar",
          "url": "poslocator-1.0.4.aar",
          "size": 123817,
          "sha512": "aad55db76a7aaa7a62d98676e518f81413be6cb63d8c77c8d22cf3e04a6249fea36d2c9ae0de0460051c5ef2ca58398aab3eacc85f29d25ef74e77181ca75608",
          "sha256": "75a7d1303e2a7c31ac40e57c7e8034f20926566d078d343c0d8454e12e1f9473",
          "sha1": "cbd799c8c07ae927126b1b101a2b405eb21e4b8a",
          "md5": "a94c4583a240b3217153a0c1a5760fdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "poslocator-1.0.4.aar",
          "url": "poslocator-1.0.4.aar",
          "size": 123817,
          "sha512": "aad55db76a7aaa7a62d98676e518f81413be6cb63d8c77c8d22cf3e04a6249fea36d2c9ae0de0460051c5ef2ca58398aab3eacc85f29d25ef74e77181ca75608",
          "sha256": "75a7d1303e2a7c31ac40e57c7e8034f20926566d078d343c0d8454e12e1f9473",
          "sha1": "cbd799c8c07ae927126b1b101a2b405eb21e4b8a",
          "md5": "a94c4583a240b3217153a0c1a5760fdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poslocator-1.0.4-sources.jar",
          "url": "poslocator-1.0.4-sources.jar",
          "size": 56507,
          "sha512": "a7bdd3119ba05bb59c8d07c3f123181ca488036d48d3e4e4239bb3625a589288054c538359309848416bcb21d942766e5cd41b12a695bdb4d196daedb2262c0c",
          "sha256": "902587d3b4560b646622806a26e6223e333c9cd9b3541891cddbec9d2bce3670",
          "sha1": "5797bfb5d733b5c9719f6a88bc356ae75ed44273",
          "md5": "d6be430cecaefb39c71f3c48e2b59160"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poslocator-1.0.4-javadoc.jar",
          "url": "poslocator-1.0.4-javadoc.jar",
          "size": 412908,
          "sha512": "64be94067aa98a006f434b484df45ad5146c323e38e9af7cda579b826391eba6305837bf0bd6c98dcb897f7da0fd464cfb3b805aacc1f4298b1e8d3475fc1242",
          "sha256": "b9371be7b9a366ae4634ca04ef5dc7159d4e890a0a81403afc5b0ed41030cf06",
          "sha1": "3080cb5b06ee016d7121318cf370904da7d3d14f",
          "md5": "b390399a14af1e6334b0bec127d97aba"
        }
      ]
    }
  ]
}
