{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ASTITeam",
    "module": "poslocator",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "poslocator-1.0.4.aar",
          "url": "poslocator-1.0.4.aar",
          "size": 167825,
          "sha512": "dcab4f48e68c5ff29fa87bd4bb1030f33c7f0341d10381c3070eedc8428c63ea0a896d2876801f8317ddca9fe6941e98dcc5a5554f8db2b44eee9b637f60a211",
          "sha256": "a5ae78789879abdf1b238873991cf05ee5b744fcf7e1430e4622f735b42978ae",
          "sha1": "a39a678d280b696aa13a491ab2909231f7b36c1c",
          "md5": "e6d25aee35668ed980816570727db73b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "appcompat-resources"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "poslocator-1.0.4.aar",
          "url": "poslocator-1.0.4.aar",
          "size": 167825,
          "sha512": "dcab4f48e68c5ff29fa87bd4bb1030f33c7f0341d10381c3070eedc8428c63ea0a896d2876801f8317ddca9fe6941e98dcc5a5554f8db2b44eee9b637f60a211",
          "sha256": "a5ae78789879abdf1b238873991cf05ee5b744fcf7e1430e4622f735b42978ae",
          "sha1": "a39a678d280b696aa13a491ab2909231f7b36c1c",
          "md5": "e6d25aee35668ed980816570727db73b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poslocator-1.0.4-sources.jar",
          "url": "poslocator-1.0.4-sources.jar",
          "size": 60817,
          "sha512": "f4fe56ea44e9f8e1b441190555731bafe480b85dd54f6479f3c42ffd5bb112a188f3bb37c7d32080c61da82f35a771e145d6cc08999afd6f2ee8e46542fd6498",
          "sha256": "eda8286750f23259e499353df6094defc7d8f0227272ff8d7b18368390b5dc36",
          "sha1": "9abc8c76b0c0c4de28d26f9ad9099c7b2300bf10",
          "md5": "cbda8c19196b73932a8577c266023680"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poslocator-1.0.4-javadoc.jar",
          "url": "poslocator-1.0.4-javadoc.jar",
          "size": 424647,
          "sha512": "d4c7a64114f50b818da7d73c53b2b780cb9f36821080d0b4e8aca82396c69cd969b05bd38ee5e2e91ba5e2ec4bef1327423069e7ed71c7ced9dd8eef0a15cd02",
          "sha256": "11aefb21c605d31b88daebcf64f5f2e95d15480c81739e964e8a2256083dbcf4",
          "sha1": "f55ffa074e033d73b6d5d0a45c0da025a2839ce5",
          "md5": "8658e6a051da1c68e57a9b7b8a715afa"
        }
      ]
    }
  ]
}
